using System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql;
using NzbWebDAV.Database;
using NzbWebDAV.Database.Models;
using Testcontainers.PostgreSql;

namespace backend.Tests.Database;

public sealed class PostgresDavMigrationTests : IClassFixture<PostgresDavMigrationFixture>
{
    private const string Cutoff = "20260419000000_FixYencLayoutColumnTypes";
    private const string LatestSetupMigration = "20260809140000_AddSetupRunLease";

    private static readonly string[] ExpectedMigrations =
    [
        "20250529081501_InitializeDatabase",
        "20250529102749_Add-CreatedAt-To-DavItem",
        "20250605030729_Add-Accounts-Table",
        "20250710072717_AddConfigItemsTable",
        "20250722004955_Ensure-Api-Key-Exists",
        "20250818232259_Add-DownloadDirId-To-HistoryItem",
        "20250819091746_Add-Ids-Root-Directory",
        "20250819221618_Add-Path-To-DavItem",
        "20250824100609_Add-IdPrefix-To-DavItems",
        "20251010192643_Add-Healthcheck-Columns-To-DavItems",
        "20251014060520_Add-HealthCheckResults-Table",
        "20251014062743_Add-HealthCheckQueue-Index",
        "20251024003729_Add-DavMultipartFiles-Table",
        "20251030163510_Add-QueueNzbContents-Table",
        "20251105050845_Add-HealthCheckStats-Table",
        "20251105200722_Add-CreatedAt-Index-To-HealthCheckResults-Table",
        "20251106165542_Ensure-Strm-Key-Exists",
        "20251113081523_Populate-Usenet-Providers-Config",
        "20260108054841_Add-BlobCleanupItems-Table",
        "20260108061241_Add-Trigger-To-QueueItems-Table",
        "20260121033824_Populate-Blocklisted-Files-Setting",
        "20260122220920_Populate-Health-Check-Categories-Setting",
        "20260406191008_AddMissingSegmentIds",
        "20260407185930_AddDeferredSpecsSchema",
        "20260414120000_AddRoleAwareNntpLeases",
        "20260414133000_AddNntpLeaseEpochs",
        "20260418120000_AddYencLayoutMetadata",
        "20260419000000_FixYencLayoutColumnTypes",
        "20260809120000_AddSetupGrants",
        "20260809130000_AddSetupMutationFenceAndCompletion",
        "20260809140000_AddSetupRunLease",
    ];

    private readonly PostgresDavMigrationFixture _fixture;

    public PostgresDavMigrationTests(PostgresDavMigrationFixture fixture) => _fixture = fixture;

    [Fact]
    public void Migrations_AreTheSingleOrderedMirroredChain()
    {
        using var context = CreateUnconnectedContext();
        Assert.Equal(ExpectedMigrations, context.Database.GetMigrations().ToArray());
        Assert.Equal(ExpectedMigrations.Length, ExpectedMigrations.Distinct(StringComparer.Ordinal).Count());
    }

    [Fact]
    public void Snapshot_HasNoPendingModelChanges_WithoutConnectingToPostgres()
    {
        using var context = CreateUnconnectedContext();
        Assert.False(context.Database.HasPendingModelChanges());
    }

    [Fact]
    public void GenerateScript_FromZeroToLatest_ContainsEveryMigrationOnce()
    {
        using var context = CreateUnconnectedContext();
        var script = context.GetService<IMigrator>().GenerateScript("0", null);

        var migrationIds = ExpectedMigrations
            .Where(script.Contains)
            .ToArray();
        Assert.Equal(ExpectedMigrations, migrationIds);
        Assert.Contains("GENERATED BY DEFAULT AS IDENTITY", script, StringComparison.Ordinal);
        Assert.Contains("__EFMigrationsHistory", script, StringComparison.Ordinal);
    }

    [Fact]
    public async Task FreshPostgres_AppliesLegacyAndSetupChain_AndUsesRuntimeMappings()
    {
        Assert.SkipUnless(_fixture.IsAvailable, "Docker with PostgreSQL 17 is required for this integration test.");
        await _fixture.ResetAsync();

        await using var context = CreateContext(_fixture.ConnectionString);
        await context.Database.MigrateAsync();
        Assert.Empty(await context.Database.GetPendingMigrationsAsync());

        context.Accounts.Add(new Account
        {
            Type = Account.AccountType.Admin,
            Username = "migration-baseline",
            PasswordHash = "hash",
            RandomSalt = "salt"
        });
        context.ConfigItems.Add(new ConfigItem
        {
            ConfigName = "migration-sentinel",
            ConfigValue = "preserved",
            IsEncrypted = false
        });
        context.SetupGrants.Add(new SetupGrant
        {
            Id = SetupGrant.SingletonId,
            GrantedTokenHash = "grant-hash",
            IssuedAtUtc = DateTime.UtcNow,
            ExpiresAtUtc = DateTime.UtcNow.AddHours(1),
            IsRevoked = false
        });
        context.SetupCompletionOperations.Add(new SetupCompletionOperation
        {
            Id = SetupCompletionOperation.SingletonId,
            OperationId = "operation-1",
            CreatedAtUtc = DateTime.UtcNow,
            RevocationPending = false
        });
        context.SetupRunLeases.Add(new SetupRunLease
        {
            Id = SetupRunLease.SingletonId,
            OwnerId = "owner-1",
            GrantHash = "grant-hash",
            Purpose = "setup",
            Generation = 1,
            LeaseUntilUtc = DateTime.UtcNow.AddMinutes(5)
        });
        var fence = await context.SetupMutationFences.SingleAsync();
        fence.Epoch = 1;
        await context.SaveChangesAsync();

        Assert.Equal("preserved", await context.ConfigItems.Where(x => x.ConfigName == "migration-sentinel").Select(x => x.ConfigValue).SingleAsync());
        Assert.Equal("migration-baseline", await context.Accounts.Select(x => x.Username).SingleAsync(x => x == "migration-baseline"));
        Assert.Equal("grant-hash", await context.SetupGrants.Select(x => x.GrantedTokenHash).SingleAsync());
        Assert.Equal(1, await context.SetupCompletionOperations.CountAsync());
        Assert.Equal(1, await context.SetupRunLeases.CountAsync());
        Assert.True(await TableExistsAsync(context, "DavItems"));
        Assert.True(await TableExistsAsync(context, "setup_grants"));
        var requiredTables = new[]
        {
            "Accounts", "DavItems", "DavNzbFiles", "DavRarFiles", "DavMultipartFiles", "QueueItems",
            "QueueNzbContents", "HistoryItems", "HealthCheckResults", "HealthCheckStats", "ConfigItems",
            "BlobCleanupItems", "MissingSegmentIds", "nntp_node_heartbeats", "nntp_connection_leases",
            "nntp_lease_epochs", "connection_pool_claims", "websocket_outbox", "auth_failures", "yenc_header_cache",
            "setup_grants", "setup_mutation_fence", "setup_completion_operations", "setup_run_leases"
        };
        var actualTables = await TableNamesAsync(context);
        Assert.True(requiredTables.All(actualTables.Contains), $"Missing tables: {string.Join(", ", requiredTables.Where(x => !actualTables.Contains(x)))}");
        Assert.Equal(ExpectedMigrations, await AppliedMigrationsAsync(context));
        Assert.Equal(ExpectedMigrations.Length, await MigrationHistoryCountAsync(context));
    }

    [Fact]
    public async Task FreshPostgres_WebsocketOutboxSeq_IsIdentityGeneratedAndIncreasing()
    {
        Assert.SkipUnless(_fixture.IsAvailable, "Docker with PostgreSQL 17 is required for this integration test.");
        await _fixture.ResetAsync();

        await using var context = CreateContext(_fixture.ConnectionString);
        await context.Database.MigrateAsync();

        context.WebsocketOutbox.Add(new WebsocketOutboxEntry
        {
            Topic = "migration-test-1",
            Payload = "payload-1"
        });
        await context.SaveChangesAsync();
        var first = await context.WebsocketOutbox
            .Where(x => x.Topic == "migration-test-1")
            .Select(x => x.Seq)
            .SingleAsync();

        context.WebsocketOutbox.Add(new WebsocketOutboxEntry
        {
            Topic = "migration-test-2",
            Payload = "payload-2"
        });
        await context.SaveChangesAsync();
        var second = await context.WebsocketOutbox
            .Where(x => x.Topic == "migration-test-2")
            .Select(x => x.Seq)
            .SingleAsync();

        Assert.NotEqual(0, first);
        Assert.True(second > first, $"Expected increasing identity sequence, got {first} then {second}.");
    }

    [Fact]
    public async Task ExistingBaselineHistory_SkipsLegacyAndAppliesOnlySetupMigrations()
    {
        Assert.SkipUnless(_fixture.IsAvailable, "Docker with PostgreSQL 17 is required for this integration test.");
        await _fixture.ResetAsync();

        await using var context = CreateContext(_fixture.ConnectionString);
        await context.Database.MigrateAsync(Cutoff);
        context.ConfigItems.Add(new ConfigItem
        {
            ConfigName = "migration-sentinel",
            ConfigValue = "survives",
            IsEncrypted = false
        });
        await context.SaveChangesAsync();
        var historyAtCutoff = await AppliedMigrationsAsync(context);
        Assert.Equal(ExpectedMigrations[..28], historyAtCutoff);

        await context.Database.MigrateAsync();

        Assert.Equal(ExpectedMigrations, await AppliedMigrationsAsync(context));
        Assert.Equal(ExpectedMigrations.Length, await MigrationHistoryCountAsync(context));
        Assert.Equal("survives", await context.ConfigItems.Where(x => x.ConfigName == "migration-sentinel").Select(x => x.ConfigValue).SingleAsync());
        Assert.True(await TableExistsAsync(context, "setup_grants"));
        Assert.True(await TableExistsAsync(context, "setup_mutation_fence"));
        Assert.True(await TableExistsAsync(context, "setup_completion_operations"));
        Assert.True(await TableExistsAsync(context, "setup_run_leases"));
    }

    [Fact]
    public async Task PostgresSetupMigrations_RollbackAndReupgrade_PreserveSentinel()
    {
        Assert.SkipUnless(_fixture.IsAvailable, "Docker with PostgreSQL 17 is required for this integration test.");
        await _fixture.ResetAsync();

        await using var context = CreateContext(_fixture.ConnectionString);
        await context.Database.MigrateAsync();
        context.ConfigItems.Add(new ConfigItem
        {
            ConfigName = "migration-roundtrip-sentinel",
            ConfigValue = "preserved",
            IsEncrypted = false
        });
        await context.SaveChangesAsync();

        await context.Database.MigrateAsync(Cutoff);
        Assert.False(await TableExistsAsync(context, "setup_run_leases"));
        Assert.Equal("preserved", await context.ConfigItems
            .Where(x => x.ConfigName == "migration-roundtrip-sentinel")
            .Select(x => x.ConfigValue)
            .SingleAsync());

        await context.Database.MigrateAsync();
        Assert.True(await TableExistsAsync(context, "setup_run_leases"));
        Assert.Equal("preserved", await context.ConfigItems
            .Where(x => x.ConfigName == "migration-roundtrip-sentinel")
            .Select(x => x.ConfigValue)
            .SingleAsync());
    }

    [Fact]
    public async Task SetupRollbackScript_FromLatestToCutoff_IsGenerated()
    {
        Assert.SkipUnless(_fixture.IsAvailable, "Docker with PostgreSQL 17 is required for this integration test.");
        await _fixture.ResetAsync();

        await using var context = CreateContext(_fixture.ConnectionString);
        await context.Database.MigrateAsync();
        var script = context.GetService<IMigrator>().GenerateScript(LatestSetupMigration, Cutoff);

        Assert.Contains("DROP TABLE setup_run_leases", script, StringComparison.Ordinal);
        Assert.Contains("DROP TABLE setup_completion_operations", script, StringComparison.Ordinal);
        Assert.Contains("DROP TABLE setup_mutation_fence", script, StringComparison.Ordinal);
        Assert.DoesNotContain("DROP TABLE \"DavItems\"", script, StringComparison.Ordinal);
    }

    private static PostgresDavMigrationContext CreateUnconnectedContext()
        => CreateContext("Host=127.0.0.1;Port=1;Database=unconnected;Username=none;Password=none;Timeout=1");

    private static PostgresDavMigrationContext CreateContext(string connectionString)
    {
        var options = new DbContextOptionsBuilder<PostgresDavMigrationContext>()
            .UseNpgsql(connectionString)
            .Options;
        return new PostgresDavMigrationContext(options);
    }

    private static async Task<string[]> AppliedMigrationsAsync(PostgresDavMigrationContext context)
        => (await context.Database.GetAppliedMigrationsAsync()).ToArray();

    private static async Task<int> MigrationHistoryCountAsync(PostgresDavMigrationContext context)
    {
        await using var command = context.Database.GetDbConnection().CreateCommand();
        if (command.Connection!.State != ConnectionState.Open)
            await command.Connection.OpenAsync();
        command.CommandText = "SELECT COUNT(*) FROM \"__EFMigrationsHistory\";";
        return Convert.ToInt32(await command.ExecuteScalarAsync());
    }

    private static async Task<bool> TableExistsAsync(PostgresDavMigrationContext context, string tableName)
    {
        await using var command = context.Database.GetDbConnection().CreateCommand();
        if (command.Connection!.State != ConnectionState.Open)
            await command.Connection.OpenAsync();
        command.CommandText = """
            SELECT EXISTS (
                SELECT 1 FROM information_schema.tables
                WHERE table_schema = 'public' AND table_name = @tableName);
            """;
        var parameter = command.CreateParameter();
        parameter.ParameterName = "tableName";
        parameter.Value = tableName;
        command.Parameters.Add(parameter);
        return Convert.ToBoolean(await command.ExecuteScalarAsync());
    }

    private static async Task<HashSet<string>> TableNamesAsync(PostgresDavMigrationContext context)
    {
        await using var command = context.Database.GetDbConnection().CreateCommand();
        if (command.Connection!.State != ConnectionState.Open)
            await command.Connection.OpenAsync();
        command.CommandText = """
            SELECT table_name
            FROM information_schema.tables
            WHERE table_schema = 'public';
            """;
        var tables = new HashSet<string>(StringComparer.Ordinal);
        await using var reader = await command.ExecuteReaderAsync();
        while (await reader.ReadAsync())
            tables.Add(reader.GetString(0));
        return tables;
    }
}

public sealed class PostgresDavMigrationFixture : IAsyncLifetime
{
    private readonly PostgreSqlContainer _container = new PostgreSqlBuilder("postgres:17-alpine")
        .WithName($"nzbdav-migrations-{Guid.NewGuid():N}")
        .WithDatabase("nzbdav")
        .WithUsername("nzbdav")
        .WithPassword("nzbdav")
        .WithCleanUp(true)
        .Build();

    public bool IsAvailable { get; private set; }
    public string ConnectionString { get; private set; } = string.Empty;

    public async ValueTask InitializeAsync()
    {
        try
        {
            await _container.StartAsync();
            ConnectionString = _container.GetConnectionString();
            IsAvailable = true;
        }
        catch
        {
            IsAvailable = false;
        }
    }

    public async ValueTask DisposeAsync() => await _container.DisposeAsync();

    public async Task ResetAsync()
    {
        if (!IsAvailable)
            return;

        await using var connection = new NpgsqlConnection(ConnectionString);
        await connection.OpenAsync();
        await using var command = connection.CreateCommand();
        command.CommandText = "DROP SCHEMA public CASCADE; CREATE SCHEMA public;";
        await command.ExecuteNonQueryAsync();
    }
}
