global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: nzbdav
    metrics_path: /metrics
    static_configs:
      - targets:
          - nzbdav-stream-1:8080
          - nzbdav-stream-2:8080
          - nzbdav-ingest:8080
        labels:
          service: nzbdav
