// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NzbWebDAV.Database;

#nullable disable

namespace NzbWebDAV.Database.Migrations
{
    [DbContext(typeof(DavDatabaseContext))]
    [Migration("20260419000000_FixYencLayoutColumnTypes")]
    partial class FixYencLayoutColumnTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("NzbWebDAV.Database.Models.Account", b =>
                {
                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RandomSalt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Type", "Username");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.AuthFailureEntry", b =>
                {
                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT")
                        .HasColumnName("ip_address");

                    b.Property<int>("FailureCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("failure_count");

                    b.Property<DateTime>("WindowStart")
                        .HasColumnType("TEXT")
                        .HasColumnName("window_start");

                    b.HasKey("IpAddress");

                    b.HasIndex("WindowStart")
                        .HasDatabaseName("ix_auth_failures_window_start");

                    b.ToTable("auth_failures", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.BlobCleanupItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BlobCleanupItems", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.ConfigItem", b =>
                {
                    b.Property<string>("ConfigName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEncrypted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.HasKey("ConfigName");

                    b.ToTable("ConfigItems", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.NntpConnectionLease", b =>
                {
                    b.Property<string>("NodeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("node_id");

                    b.Property<int>("ProviderIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("provider_index");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role");

                    b.Property<int>("BorrowedSlots")
                        .HasColumnType("INTEGER")
                        .HasColumnName("borrowed_slots");

                    b.Property<long>("Epoch")
                        .HasColumnType("INTEGER")
                        .HasColumnName("epoch");

                    b.Property<int>("GrantedSlots")
                        .HasColumnType("INTEGER")
                        .HasColumnName("granted_slots");

                    b.Property<DateTime>("LeaseUntil")
                        .HasColumnType("TEXT")
                        .HasColumnName("lease_until");

                    b.Property<int>("ReservedSlots")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reserved_slots");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("NodeId", "ProviderIndex");

                    b.HasIndex("LeaseUntil")
                        .HasDatabaseName("ix_nntp_connection_leases_lease_until");

                    b.ToTable("nntp_connection_leases", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.NntpLeaseEpoch", b =>
                {
                    b.Property<int>("ProviderIndex")
                        .ValueGeneratedNever()
                        .HasColumnType("INTEGER")
                        .HasColumnName("provider_index");

                    b.Property<long>("Epoch")
                        .HasColumnType("INTEGER")
                        .HasColumnName("epoch");

                    b.HasKey("ProviderIndex");

                    b.ToTable("nntp_lease_epochs", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.NntpNodeHeartbeat", b =>
                {
                    b.Property<string>("NodeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("node_id");

                    b.Property<int>("ProviderIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("provider_index");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role");

                    b.Property<int>("ActiveSlots")
                        .HasColumnType("INTEGER")
                        .HasColumnName("active_slots");

                    b.Property<int>("DesiredSlots")
                        .HasColumnType("INTEGER")
                        .HasColumnName("desired_slots");

                    b.Property<bool>("HasDemand")
                        .HasColumnType("INTEGER")
                        .HasColumnName("has_demand");

                    b.Property<DateTime>("HeartbeatAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("heartbeat_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("LiveSlots")
                        .HasColumnType("INTEGER")
                        .HasColumnName("live_slots");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("region");

                    b.HasKey("NodeId", "ProviderIndex");

                    b.HasIndex("HeartbeatAt")
                        .HasDatabaseName("ix_nntp_node_heartbeats_heartbeat_at");

                    b.ToTable("nntp_node_heartbeats", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.ConnectionPoolClaim", b =>
                {
                    b.Property<string>("NodeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("node_id");

                    b.Property<int>("ProviderIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("provider_index");

                    b.Property<int>("ClaimedSlots")
                        .HasColumnType("INTEGER")
                        .HasColumnName("claimed_slots");

                    b.Property<DateTime>("HeartbeatAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("heartbeat_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("NodeId", "ProviderIndex");

                    b.HasIndex("HeartbeatAt")
                        .HasDatabaseName("ix_connection_pool_claims_heartbeat_at");

                    b.ToTable("connection_pool_claims", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.DavItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdPrefix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastHealthCheck")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long?>("NextHealthCheck")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ReleaseDate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("YencPartSize")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("YencLastPartSize")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("YencSegmentCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("YencLayoutUniform")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdPrefix", "Type");

                    b.HasIndex("ParentId", "Name")
                        .IsUnique();

                    b.HasIndex("Type", "NextHealthCheck", "ReleaseDate", "Id");

                    b.ToTable("DavItems", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.DavMultipartFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DavMultipartFiles", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.DavNzbFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("SegmentIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DavNzbFiles", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.DavRarFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("RarParts")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DavRarFiles", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.HealthCheckResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DavItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RepairStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Result")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DavItemId")
                        .HasFilter("\"RepairStatus\" = 3");

                    b.HasIndex("Result", "RepairStatus", "CreatedAt");

                    b.ToTable("HealthCheckResults", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.HealthCheckStat", b =>
                {
                    b.Property<long>("DateStartInclusive")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DateEndExclusive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Result")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RepairStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.HasKey("DateStartInclusive", "DateEndExclusive", "Result", "RepairStatus");

                    b.ToTable("HealthCheckStats", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.HistoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DownloadDirId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DownloadStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DownloadTimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalSegmentBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Category", "CreatedAt");

                    b.HasIndex("Category", "DownloadDirId");

                    b.ToTable("HistoryItems", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.MissingSegmentId", b =>
                {
                    b.Property<string>("SegmentId")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long>("DetectedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("SegmentId");

                    b.ToTable("MissingSegmentIds", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.QueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("NzbFileSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PauseUntil")
                        .HasColumnType("TEXT");

                    b.Property<int>("PostProcessing")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalSegmentBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FileName")
                        .IsUnique();

                    b.HasIndex("Priority");

                    b.HasIndex("Priority", "CreatedAt");

                    b.HasIndex("Category", "Priority", "CreatedAt");

                    b.ToTable("QueueItems", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.QueueNzbContents", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("NzbContents")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("QueueNzbContents", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.WebsocketOutboxEntry", b =>
                {
                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("seq");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("topic");

                    b.HasKey("Seq");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_websocket_outbox_created_at");

                    b.ToTable("websocket_outbox", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.YencHeaderCacheEntry", b =>
                {
                    b.Property<string>("SegmentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("segment_id");

                    b.Property<DateTime>("CachedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("cached_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_size");

                    b.Property<int>("LineLength")
                        .HasColumnType("INTEGER")
                        .HasColumnName("line_length");

                    b.Property<int>("PartNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("part_number");

                    b.Property<long>("PartOffset")
                        .HasColumnType("INTEGER")
                        .HasColumnName("part_offset");

                    b.Property<long>("PartSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("part_size");

                    b.Property<int>("TotalParts")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_parts");

                    b.HasKey("SegmentId");

                    b.HasIndex("CachedAt")
                        .HasDatabaseName("ix_yenc_header_cache_cached_at");

                    b.ToTable("yenc_header_cache", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.DavItem", b =>
                {
                    b.HasOne("NzbWebDAV.Database.Models.DavItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.DavMultipartFile", b =>
                {
                    b.HasOne("NzbWebDAV.Database.Models.DavItem", "DavItem")
                        .WithOne()
                        .HasForeignKey("NzbWebDAV.Database.Models.DavMultipartFile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DavItem");
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.DavNzbFile", b =>
                {
                    b.HasOne("NzbWebDAV.Database.Models.DavItem", "DavItem")
                        .WithOne()
                        .HasForeignKey("NzbWebDAV.Database.Models.DavNzbFile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DavItem");
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.DavRarFile", b =>
                {
                    b.HasOne("NzbWebDAV.Database.Models.DavItem", "DavItem")
                        .WithOne()
                        .HasForeignKey("NzbWebDAV.Database.Models.DavRarFile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DavItem");
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.QueueNzbContents", b =>
                {
                    b.HasOne("NzbWebDAV.Database.Models.QueueItem", "QueueItem")
                        .WithOne()
                        .HasForeignKey("NzbWebDAV.Database.Models.QueueNzbContents", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QueueItem");
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.DavItem", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
